# bedrock-values.yaml
# Credentials managed via SSM Parameter Store + Terraform
# Passwords are NEVER stored in this file

catalog:
  app:
    persistence:
      provider: mysql
      endpoint: bedrock-mysql.cedysk464ef6.us-east-1.rds.amazonaws.com:3306
      database: catalog
      secret:
        create: false
        name: catalog-db
  mysql:
    create: false

orders:
  app:
    persistence:
      provider: postgresql
      endpoint: bedrock-postgres.cedysk464ef6.us-east-1.rds.amazonaws.com:5432
      database: orders
      secret:
        create: false
        name: orders-db
    messaging:
      provider: in-memory
  postgresql:
    create: false

carts:
  app:
    persistence:
      provider: dynamodb
      dynamodb:
        tableName: items
        createTable: false
  dynamodb:
    create: false
