# bedrock-values.yaml

# 1. Configure the Catalog Microservice (Connects to PostgreSQL)
catalog:
  postgresql:
    enabled: false # Disables the fragile in-cluster Postgres pod
  db:
    endpoint: bedrock-postgres.cozk2e2oeu9c.us-east-1.rds.amazonaws.com:5432
    name: retaildb
    username: dbadmin
    password: SecureBedrockPass2026!

# 2. Configure the Orders Microservice (Connects to MySQL)
orders:
  mysql:
    enabled: false # Disables the fragile in-cluster MySQL pod
  db:
    endpoint: bedrock-mysql.cozk2e2oeu9c.us-east-1.rds.amazonaws.com:3306
    name: orders
    username: dbadmin
    password: SecureBedrockPass2026!

# 3. Configure the Carts Microservice (Bypasses local DB for real DynamoDB)
carts:
  dynamodb:
    enabled: false # Disables the local mock DynamoDB pod; forces use of real AWS DynamoDB

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
