app:
  persistence:
    provider: mysql
    endpoint: bedrock-mysql.cedysk464ef6.us-east-1.rds.amazonaws.com:3306
    database: catalog
    secret:
      create: false
      name: catalog-db
mysql:
  create: false
