name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform Engine'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }} #AKIAXP24JV4NX6SIF5UK # ${{ secrets.AWS_ACCESS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4

      - name: Setup Terraform Engine
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

     # - name: Debug Secrets
      #  run: |
       #   echo "ACCESS KEY LENGTH:"
        #  echo ${#AWS_ACCESS_KEY_ID}

         # echo "SECRET KEY LENGTH:"
          #echo ${#AWS_SECRET_ACCESS_KEY}

      - name: Validate AWS Secret Ingestion
        run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "❌ CRITICAL ERROR: GitHub Secrets are resolving to EMPTY strings."
            echo "Ensure repository secrets are named EXACTLY:"
            echo "AWS_ACCESS_KEY_ID"
            echo "AWS_SECRET_ACCESS_KEY"
            exit 1
          else
            echo "✅ GitHub Secrets successfully ingested."
          fi

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Apply & Artifact Export
        run: |
          terraform -chdir=terraform apply -auto-approve
          terraform -chdir=terraform output -json > grading.json

      - name: Archive Submission Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capstone-grading-deliverable
          path: grading.json
